config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#login"

  get "/overview" => "clubs#overview"

  resources :users, only: [:update] do
  end
  
  get "/account" => "users#manage_account"
  get "/library" => "books#completed"

  resources :sessions, only: [:create, :destroy]

  get "/meetings/:id/edit" => "meetings#edit"
  get "/meetings/new" => "meetings#new"
  post "/meetings" => "meetings#create"
  put "/meetings/:id" => "meetings#update"

  resources :books, only: [:create] do
    member do
      post "/mark_read" => "books#mark_read"

      get "/reviews" => "reviews#index"
      post "/reviews" => "reviews#create"
      put "/reviews" => "reviews#edit"
      delete "/reviews" => "reviews#destroy"
    end

    collection do
      get "/add_read" => "books#add_read"
    end
  end

  resources :book_search, controller: "book_search", only: [:index]

  resources :collections, only: [] do
    member do
      get "/new_book" => "collections#new_book"
      post "/add" => "collections#add"
    end
  end

  resources :members, only: [:show] do 
  end

  resources :nominations, only: [:new, :create, :destroy, :index, :update] do
    member do
      delete "/downvote" => "nominations#downvote", as: "downvote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :books_collections, class_name: "BooksCollections"
  has_many :collections, through: :books_collections
  has_many :reviews

  def reviewed_by?(member)
    reviews.exists?(member_id: member.id)
  end
end

app/models/books_collections.rb
class BooksCollections < ActiveRecord::Base
  belongs_to :collection
  belongs_to :book
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :meetings
    has_many :members
    has_many :collections, as: :owner
    
    def create_member!(member_name)
      first, last = member_name.split(" ")
      members.create!(
          first_name: first,
          last_name: last
      )
    end

    def upcoming_meetings
      meetings.upcoming
    end

    def next_meeting
      meetings.upcoming.first || NullMeeting.new
    end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  self.inheritance_column = ""
  belongs_to :owner, polymorphic: true
  has_many :books_collections, class_name: "BooksCollections"
  has_many :books, through: :books_collections 

  module Types
    READ = "READ"
    TO_READ = "TO_READ"

    ALL = [READ, TO_READ]
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :book
  scope :upcoming, -> { where("held_on > '#{Date.today}'").order(:held_on) }

  def book
    super || NullBook.new
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :club
  has_many :nominations
  has_many :collections, as: :owner

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/nomination.rb
class Nomination < ApplicationRecord
    belongs_to :book
    belongs_to :member
    has_many :votes

    validates :member_id, uniqueness: { message: 'may only nominate one book at a time' }
end

app/models/null_book.rb
class NullBook
  def title
    "TBD"
  end
end

app/models/null_meeting.rb
class NullMeeting
    def held_on
        "unspecified"
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :member

  def written_by?(_member)
    _member == member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :member
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :member
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def completed
    @books = current_club.collections.find_by(type: Collection::Types::READ).books
  end

  def create
    raise "No such collection type" unless Collection::Types::ALL.include?(params[:collection_type])
    collection = current_club.collections.find_by(type: params[:collection_type])

    book = Book.find_or_create_by!(title: params[:title], author: params[:author])
    Books::SynchronizeBook.new(book).call

    collection.books << book

    redirect_to :library
  end

  def mark_read
    Books::ReadNomination.new(params_with_club).call
  end

  private

  def params_with_club
    params.merge({
      book_id: params[:id],
      club: current_club
    })
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    def overview
        club = Club.find(current_user.member.club_id)

        @overview = ClubOverview.new(club, current_member)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def create
    unless meeting_param[:held_on].present?
      redirect_to meetings_new_path, { flash: { error: "Please include all fields" } } and return
    end

    Meetings::Create.new(meeting_param.merge(club_id: current_club.id)).call
    redirect_to overview_path
  end

  def edit
    @meeting = Meeting.find(params["id"])

    @meeting_options = {
      books: book_options
    }
  end

  def new
    @meeting_options = {
      books: book_options
    }
  end

  def update
    Meetings::UpdateMeeting.new(params).call

    redirect_to overview_path
  end

  private

  def book_options
    NominationsQuery.new.all.map do |book|
      [book.title, book.id]
    end.append([NullBook.new.title, nil])
  end

  def meeting_param
    params[:meeting]
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    current_member
    @member = MemberWithCollections.new(Member.find(params[:id]))
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    current_member
    @book = Book.find(params[:id])
  end

  def create
    @review = Books::Review.new(book_params).call

    render "create.js.erb"
  end

  def destroy
    @review = Review.find_by!(book_id: params[:id], member_id: current_member.id).destroy!

    render "destroy.js.erb"
  end

  def edit
    @review = Review.find_by(
      book_id: params[:id], 
      member_id: current_member.id
    )
    
    @review.update_attributes!(editable_params)
    @review.reload

    render "edit.js.erb"
  end

  private

  def book_params
    params.merge({
      book_id: params[:id],
      member_id: current_member.id
    })
  end

  def editable_params
    params.slice(:text).permit!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def manage_account; end

    def update
        begin
            Users::ChangePassword.new(
                current_user,
                params[:current_password],
                params[:new_password],
                params[:new_password_confirmation]
            ).call
            
            flash[:success] = true
        rescue => e
            flash[:alert] = e.message
        end

        redirect_to account_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="fill-page">
  <head>
    <title>Bookclub</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/84c3412e64.js" crossorigin="anonymous"></script> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- from favicon.io -->
    <%= favicon_link_tag asset_path('favicon-16x16.png') %>
  </head>

  <body class="fill-page">
    <div class="pure-g fill-page background-grey">
      <div class="pure-u-4-24"></div>
      <div class="pure-u-16-24">
        <%= render partial: "/header_menu" if @current_user %>
        <div id="content">
          <%= yield %>
         </div>
      </div>
      <div class="pure-u-4-24"></div>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html class="fill-page">
  <head>
    <title>Bookclub</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/84c3412e64.js" crossorigin="anonymous"></script> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- from favicon.io -->
    <%= favicon_link_tag asset_path('favicon-16x16.png') %>
  </head>

  <body class="fill-page">
    <div class="pure-g fill-page background-grey">
      <div class="pure-u-4-24"></div>
      <div class="pure-u-16-24">
        <%= render partial: "/header_menu" if @current_user %>
        <div id="content">
          <%= yield %>
         </div>
      </div>
      <div class="pure-u-4-24"></div>
    </div>
  </body>

  <!-- TODO: atttributions in footer -->
  <!-- Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a> -->
</html>

app/views/nominated_books/_nominated_book.html.erb
<tr class="pure-g nominated-book-<%= nominated_book.nomination.id %>">

    <!-- Upvote Button -->
    <td class="pure-u-1-4 upvotes-<%= nominated_book.nomination.id %>">
        <% if nominated_book.upvoted_by?(@current_user) %>
            <%= link_to(downvote_nomination_path(nominated_book.nomination), { remote: true, method: :delete, class: "pure-button"}) do %>
                <span><%= nominated_book.upvotes %></span>
                <i class="fas fa-thumbs-up"></i>
            <% end %>
        <% else %>
            <%= link_to(nomination_path(nominated_book.nomination.id), { remote: true, method: :put, class: "pure-button" }) do %>
                <span><%= nominated_book.upvotes %></span>
                <i class="far fa-thumbs-up"></i>
            <% end %>
        <% end %>
    </td>

    <!-- Book details -->
    <td class="pure-u-1-2">
        <span>
            <span><%= "#{nominated_book.title} by #{nominated_book.author}" %></span>
            <small data-toggle-show="description-<%= nominated_book.nomination.id %>">More</small>
        <span>
        <p>
            <small id="description-<%= nominated_book.nomination.id %>" hidden>
                <%= nominated_book.description %>
            </small>
        </p>
    </td>

    <!-- Nomination Actions -->
    <td
      data-toggle-actions="dropdown-<%= nominated_book.nomination.id %>" 
      class="nomination-actions pure-u-1-4"
    >
      <div class="nomination-actions-dropdown" id="dropdown-<%= nominated_book.nomination.id %>">
        <ul>
          <li><%= render partial: "nominations/book_link", object: nominated_book %></li>
          <li>
            <%= link_to(mark_read_book_path(nominated_book.book.id), { remote: true, method: :post}) do %>
              <i class="fas fa-book" title="Mark as Read"></i>
              <span>Mark read</span>
            <% end %>
          </li>
          <li>
            <%= link_to("X Remove", nomination_path(nominated_book.nomination.id), { remote: true, method: :delete}) if nominated_book.nominated_by?(@current_user) %>
          </li>
        </ul>
      </div>
    </td>
</tr>