config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#login"

  get "/overview" => "clubs#overview"

  resources :users, only: [:update] do
  end
  
  get "/account" => "users#manage_account"
  get "/library" => "books#completed"

  resources :sessions, only: [:create, :destroy]

  get "/meetings/:id/edit" => "meetings#edit"
  get "/meetings/new" => "meetings#new"
  post "/meetings" => "meetings#create"
  put "/meetings/:id" => "meetings#update"

  resources :books, only: [:create] do
    member do
      post "/mark_read" => "books#mark_read"

      get "/reviews" => "reviews#index"
      post "/reviews" => "reviews#create"
      put "/reviews" => "reviews#edit"
      delete "/reviews" => "reviews#destroy"
    end

    collection do
      get "/add_read" => "books#add_read"
    end
  end

  resources :book_search, controller: "book_search", only: [:index]

  resources :collections, only: [] do
    member do
      get "/new_book" => "collections#new_book"
      post "/add" => "collections#add"
    end
  end

  resources :members, only: [:show] do 
  end

  resources :nominations, only: [:new, :create, :destroy, :index, :update] do
    member do
      delete "/downvote" => "nominations#downvote", as: "downvote"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :books_collections, class_name: "BooksCollections"
  has_many :collections, through: :books_collections
  has_many :reviews

  def reviewed_by?(member)
    reviews.exists?(member_id: member.id)
  end
end

app/models/books_collections.rb
class BooksCollections < ActiveRecord::Base
  belongs_to :collection
  belongs_to :book
end

app/models/club.rb
class Club < ApplicationRecord
    has_many :meetings
    has_many :members
    has_many :collections, as: :owner
    
    def create_member!(member_name)
      first, last = member_name.split(" ")
      members.create!(
          first_name: first,
          last_name: last
      )
    end

    def upcoming_meetings
      meetings.upcoming
    end

    def next_meeting
      meetings.upcoming.first || NullMeeting.new
    end
end

app/models/collection.rb
class Collection < ActiveRecord::Base
  self.inheritance_column = ""
  belongs_to :owner, polymorphic: true
  has_many :books_collections, class_name: "BooksCollections"
  has_many :books, through: :books_collections 

  module Types
    READ = "READ"
    TO_READ = "TO_READ"

    ALL = [READ, TO_READ]
  end
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :book
  scope :upcoming, -> { where("held_on > '#{Date.today}'").order(:held_on) }

  def book
    super || NullBook.new
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :club
  has_many :nominations
  has_many :collections, as: :owner

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/nomination.rb
class Nomination < ApplicationRecord
    belongs_to :book
    belongs_to :member
    has_many :votes

    validates :member_id, uniqueness: { message: 'may only nominate one book at a time' }
end

app/models/null_book.rb
class NullBook
  def title
    "TBD"
  end
end

app/models/null_meeting.rb
class NullMeeting
    def held_on
        "unspecified"
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :member

  def written_by?(_member)
    _member == member
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :member
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  protect_from_forgery with: :exception

  def current_club
    current_member && current_member.club
  end

  def current_user
    return unless session[:user_id]
    
    @current_user = User.find(session[:user_id])
  end

  def current_member
    @current_member = current_user.member
  end

  private

  def require_login
    unless current_user
      redirect_to root_url
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def completed
    @books = current_club.collections.find_by(type: Collection::Types::READ).books
  end

  def create
    raise "No such collection type" unless Collection::Types::ALL.include?(params[:collection_type])
    collection = current_club.collections.find_by(type: params[:collection_type])

    book = Book.find_or_create_by!(title: params[:title], author: params[:author])
    Books::SynchronizeBook.new(book).call

    collection.books << book

    redirect_to :library
  end

  def mark_read
    Books::ReadNomination.new(params_with_club).call
  end

  private

  def params_with_club
    params.merge({
      book_id: params[:id],
      club: current_club
    })
  end
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
    def overview
        club = Club.find(current_user.member.club_id)

        @overview = ClubOverview.new(club, current_member)
    end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  def create
    unless meeting_param[:held_on].present?
      redirect_to meetings_new_path, { flash: { error: "Please include all fields" } } and return
    end

    Meetings::Create.new(meeting_param.merge(club_id: current_club.id)).call
    redirect_to overview_path
  end

  def edit
    @meeting = Meeting.find(params["id"])

    @meeting_options = {
      books: book_options
    }
  end

  def new
    @meeting_options = {
      books: book_options
    }
  end

  def update
    Meetings::UpdateMeeting.new(params).call

    redirect_to overview_path
  end

  private

  def book_options
    NominationsQuery.new.all.map do |book|
      [book.title, book.id]
    end.append([NullBook.new.title, nil])
  end

  def meeting_param
    params[:meeting]
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def show
    current_member
    @member = MemberWithCollections.new(Member.find(params[:id]))
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    current_member
    @book = Book.find(params[:id])
  end

  def create
    @review = Books::Review.new(book_params).call

    render "create.js.erb"
  end

  def destroy
    @review = Review.find_by!(book_id: params[:id], member_id: current_member.id).destroy!

    render "destroy.js.erb"
  end

  def edit
    @review = Review.find_by(
      book_id: params[:id], 
      member_id: current_member.id
    )
    
    @review.update_attributes!(editable_params)
    @review.reload

    render "edit.js.erb"
  end

  private

  def book_params
    params.merge({
      book_id: params[:id],
      member_id: current_member.id
    })
  end

  def editable_params
    params.slice(:text).permit!
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :login]

  def login
    if current_user
      redirect_to overview_url
    else
      render layout: "landing"
    end
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to overview_url
    else
      flash.now[:alert] = "Email or password invalid"
      render "login"
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def manage_account; end

    def update
        begin
            Users::ChangePassword.new(
                current_user,
                params[:current_password],
                params[:new_password],
                params[:new_password_confirmation]
            ).call
            
            flash[:success] = true
        rescue => e
            flash[:alert] = e.message
        end

        redirect_to account_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_book.html.erb
<li class="pure-g book-list-item">
  <div class="pure-u-2-8">
    <img height=80% width=80% src=<%= book.thumbnail || "" %> />
  </div>
  <div class="pure-u-5-8">
    <p><i><%= "#{book.title}" %></i></p>
    <p><%= "#{book.author}"%></p>
  </div>
  <div class="pure-u-1-8">
    <a href=<%= %"/books/#{book.id}/reviews" %>><i class="far fa-comments"></i></a>
  </div>
</li>

app/views/books/add_read.html.erb
<h1>Add to library</h1>
<%= form_with(url: "/books", method: "post", class: "pure-form-stacked") do %>
    <%= label_tag(:title, "Title") %>
    <%= text_field_tag(:title) %>
    <%= label_tag(:author, "Author") %>
    <%= text_field_tag(:author) %>
    <%= hidden_field(nil, :collection_type, value: Collection::Types::READ)%>
    <%= submit_tag("Add") %>
<% end %>

app/views/books/completed.html.erb
<h2>Library</h2>

<%= link_to("Add to library", add_read_books_path, class: "pure-button") %>
<ul>
  <%=  render(@books) %>
</ul>

app/views/meetings/_meeting.html.erb
<li>
  <span>
    <span><%= meeting.held_on.strftime("%b %e %Y") %></span>
    Book Discussion: 
    <i><%= meeting.book.title %></i>
    <a class="pure-button button-xsmall" href= <%= "/meetings/#{meeting.id}/edit" %>>Edit</a>
    </span>
</li>

app/views/meetings/edit.html.erb
<h1>Edit Meeting</h1>
<%= form_with(url: "/meetings/#{@meeting.id}", method: "put", class: "pure-form-stacked") do %>
  <%= label_tag(:book, "Book") %>
  <%= select(:meeting, :book_id, @meeting_options[:books])%>
  <%= label_tag(:meeting_held_on, "Meeting Date")%>
  <%= date_field(:meeting, :held_on) %>
  <%= submit_tag("Submit Changes") %>
<% end %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>
<% if flash %>
  <p><%= flash[:error] %>
<% end %>

<%= form_with(url: "/meetings", method: "post", class: "pure-form-stacked") do %>
  <%= label_tag(:book, "Book") %>
  <%= select(:meeting, :book_id, @meeting_options[:books])%>
  <%= label_tag(:meeting_held_on, "Meeting Date")%>
  <%= date_field(:meeting, :held_on) %>
  <%= submit_tag("Add Meeting") %>
<% end %>

app/views/members/show.html.erb
<h2><%= "#{@member.first_name} #{@member.last_name}"%></h2>

<h3>Reading List</h3>

<h4>To Read</h4>
<%= link_to("Add a book", new_book_collection_path(@member.to_read_collection.id), class: "pure-button") if @member.is?(@current_member)%>
<%= render(@member.books_to_read) %>

app/views/users/manage_account.html.erb
<%= form_with(url: "users/#{@current_user.id}", method: "put", class: "pure-form-stacked") do %>
    <%= label_tag(:current_password, "Current Password: ") %>
    <%= password_field_tag(:current_password) %>
    <%= label_tag(:new_password, "New Password: ") %>
    <%= password_field_tag(:new_password) %>
    <%= label_tag(:new_password_confirmation, "Confirm New Password: ") %>
    <%= password_field_tag(:new_password_confirmation) %>
    <%= submit_tag("Okie doke") %>
<% end %>
<% if flash[:alert] %>
    <p class="form-alert">Error: <%= flash[:alert] %></p>
<% elsif flash[:success] %>
    <p class="form-success">Success!</p>
<% end %>